name: vewin
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  flutter_otp_text_field: ^1.1.1
  dio: ^5.3.3
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  network_info_plus: ^4.0.2
  pretty_dio_logger: ^1.3.1
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  image: ^4.1.3
  path_provider: ^2.1.1
  win32: ^5.12.0





dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  retrofit_generator:

flutter:
  uses-material-design: true

  fonts:
   - family: Poppins-Light
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
   - family: Poppins-Medium
     fonts:
       - asset: assets/fonts/Poppins-Medium.ttf    
   - family: Poppins-Regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf   
   - family: Poppins-SemiBold
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf

  assets:
   - assets/images/
   - assets/icons/
   - assets/gif/

